version: '3.8'

services:
  meraki-llm:
    build:
      context: ./meraki-llm
      dockerfile: Dockerfile
    env_file:
      - ./meraki-llm/.env
    volumes:
      # Mount the agent code for easier development (optional, remove for production)
      - ./meraki-llm/agent:/app/agent 

  streamlit-chat:
    build:
      context: ./streamlit-chat
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./streamlit-chat/.env
    depends_on:
      - meraki-llm